### ISSUE TITLE
vlsub hangs during the search

### ISSUE THREAD

**Issue by luigino** [exebetche/vlsub#115]
As per subject, it started today.
Relevant log here: http://pastebin.com/8AgS23sc

**Comment by luigino** [comment]
Works now, must have been a temporary server glitch.

**Comment by olacirjr** [comment]
I have the exactly same problem, but discovered the reason.
When I am searching for a video that does not have subtitle yet, instead of showing the the error message, vlsub hangs. They probably changed something in the opensubtitles api.
When I am searching for another video where subtitles are available there is no problem.
