### ISSUE TITLE
VLsub error and does not start

### ISSUE THREAD

**Issue by Deschain** [exebetche/vlsub#28]
VLsub extension does not start in VLC 2.1.0 (Rincewind) 64bit edition under Windows 7

Here is the log of the error, hope it helps

```
qt4 debug: activating or triggering extension 'VLsub 0.9.10'
lua debug: Activating extension 'VLsub 0.9.10'
lua debug: [VLsub] Welcome
lua debug: [VLSub] Working directory: C:\Users\FakeName\AppData\Roaming\vlc\lua\extensions\userdata\vlsub
lua debug: [VLSub] Loading config file: C:\Users\FakeName\AppData\Roaming\vlc\lua\extensions\userdata\vlsub\vlsub_conf.xml
lua debug: [VLSub] Video URI: file:///D:/Dowloads/Complete.Legal.Content.mp4
lua warning: Error while running script C:\Program Files\VideoLAN\VLC\lua\extensions\vlsub.lua, function activate(): ...\Program Files\VideoLAN\VLC\lua\extensions\vlsub.lua:1184: attempt to index field 'net' (a nil value)
lua error: Could not activate extension!
lua debug: Deactivating 'VLsub 0.9.10'
lua debug: [VLsub] Bye bye!
lua debug: Extension thread end: 'VLsub 0.9.10'
```

**Comment by exebetche** [comment]
Vlc 2.2 is out.

**Comment by MaximusMeridias** [comment]
I know this is an old thread, but just for the chance that someone still having trouble with vlsub not finishing the download stumble across here. I just fixed this problem of not finished subtitle download on my system. 

In my case I switched from windows 7 to windows 10 (clean install, no upgrade). Problem occured on my NTFS datadisc holding my media (obviously not refreshed after windows install.) VLsub would hash the file, find a (or more) result(s), when clicking the download button the progressbar appears 100% green, but the process never finishes. Latest version VLC 2.2.4 did not work for me, so tried 2.2.0. No dice either. 

Allthough this was not actually the cause, but the hint on vlsubs' site is what lead me in the right direction: "Due to some bugs on Windows, if the path to your video contain non-english characters, the extension will not be able to save subtitles in this directory automatically". 

The media in question was burried 4 folders deep in my collection. There were no non-english characters in the path however. I used a # though, in the top folder called "# Series". Thought that might be the cause, so I moved the mediafile to the root of my disc, and...

VOILA! Subs got downloaded!

After that I couldn't quite believe # would cause this kind of a problem, so I tried putting the mediafile in a new map with a # in the name: "# test" And again no problem (!). So the # cannot be the problem. Then I renamed the "# Series" to "temp" and and "# test" to "# Series"  and moved the entire collection from "temp" to the new "#Series" folder 
-> Problem solved!  

Seems the top-folder of the tree was somehow causing the problem. Maybe NTFS rights and/or user-id's not being equal or something. (Using same username as the old windows) This goes to deep for me, but I did fix my problem this way. I spend half my evening on this shit, hope this helps someone else out, if not, alert some developer of this malfunction. :)

**Comment by harish-myaccount** [comment]
Vlsub crashing with error
mkdir: cannot create directory ‘/usr/share/vlc/lua/extensions’: Permission denied
Elementary OS loki
Vlc 2.2.2

**Comment by exebetche** [comment]
@harish-myaccount put the updated script in [[your home directory]]/.local/share/vlc/lua/extensions/ instead

**Comment by harish-myaccount** [comment]
Thanks for quick reply.
Copying the script worked fine.But gave two menu options
Download subtitles (one given by VLC by default...this didn't work)
VLSub(this is working fine)

**Comment by exebetche** [comment]
@harish-myaccount You have to remove the old one, I don't your OS specifics but maybe this will do:
`sudo rm /usr/lib/vlc/lua/VLSub.luac`
or 
`sudo rm /usr/share/vlc/lua/extensions/VLSub.luac`

**Comment by harish-myaccount** [comment]
yeah
sudo rm /usr/lib/vlc/lua/extensions/VLSub.luac 
removed that menu option.
Thanks

Elementary OS - Loki is fork of ubuntu 16.04
